name: Update dns.txt

on:
  workflow_dispatch: # permite rodar manualmente
  schedule:
    - cron: "0 * * * *" # roda de hora em hora (ajuste se quiser)

jobs:
  update-dns:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 🔑 permite push com o GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Python script
        run: |
          python script.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add dns.txt
          git diff --cached --quiet || git commit -m "Update dns.txt"

      - name: Push changes
        run: |
          git push
